package com.example.foundbuddybackend.controller;

import com.example.foundbuddybackend.model.User;
import com.example.foundbuddybackend.repository.UserRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/**
 * REST controller for managing user profiles.  Note that no authentication
 * mechanism is implemented; any caller can create, update or delete users.
 */
@RestController
@RequestMapping("/api/users")
@CrossOrigin(origins = "*")
public class UserController {

    private final UserRepository repository;

    public UserController(UserRepository repository) {
        this.repository = repository;
    }

    /**
     * Returns all users.  In many scenarios the application only needs a
     * single user profile, but returning a list allows for future
     * multi‑user support.
     */
    @GetMapping
    public List<User> getAll() {
        return repository.findAll();
    }

    /**
     * Retrieves a single user by id.
     */
    @GetMapping("/{id}")
    public ResponseEntity<User> getById(@PathVariable Long id) {
        Optional<User> user = repository.findById(id);
        return user.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Creates a new user profile.  The {@code id} field is ignored and
     * generated by the database.
     */
    @PostMapping
    public ResponseEntity<User> create(@RequestBody User user) {
        user.setId(null);
        User saved = repository.save(user);
        return new ResponseEntity<>(saved, HttpStatus.CREATED);
    }

    /**
     * Updates an existing user profile.  If the user does not exist, HTTP 404
     * is returned.
     */
    @PutMapping("/{id}")
    public ResponseEntity<User> update(@PathVariable Long id, @RequestBody User updated) {
        return repository.findById(id).map(existing -> {
            existing.setUserName(updated.getUserName());
            existing.setFullName(updated.getFullName());
            existing.setBio(updated.getBio());
            existing.setProfileImageUri(updated.getProfileImageUri());
            User saved = repository.save(existing);
            return new ResponseEntity<>(saved, HttpStatus.OK);
        }).orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Deletes a user by id.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        if (!repository.existsById(id)) {
            return ResponseEntity.notFound().build();
        }
        repository.deleteById(id);
        return ResponseEntity.noContent().build();
    }
}