# ======================
# FIREBASE BACKEND CONFIG
# ======================

# Name der App (optional)
spring.application.name=FoundBuddyBackend

# Server-Port (kannst du ändern)
server.port=8080

# Logging (optional)
logging.level.root=INFO
logging.level.com.google.firebase=INFO

# H2 und JPA deaktivieren (nicht mehr nötig)
spring.h2.console.enabled=false
spring.datasource.url=
spring.jpa.hibernate.ddl-auto=none
