services:
  # 1) CLIP Service auf Hugging Face (extern)
  # - wird auf Hugging Face Spaces deployed

  # 2) Backend Service
  - type: web
    name: foundbuddy-backend
    env: docker
    rootDir: FoundBuddy-backend
    plan: free
    autoDeploy: true
    envVars:
      - key: CLIP_URL
        value: https://huggingface.co/spaces/MartlSpedl/foundbuddy-clip

