package com.example.foundbuddybackend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Simple user entity corresponding to a profile in the FoundBuddy front‑end.
 *
 * <p>
 * Each user has a unique id generated by the database, a public user
 * name, an optional full name and bio, and an optional profile image URI.  No
 * authentication is provided by this backend; it simply stores arbitrary
 * profiles posted by the client.
 */
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    private String userName;

    private String fullName;

    @Column(length = 4096)
    private String bio;

    private String profileImageUri;

    public User() {}

    public User(String userName, String fullName, String bio, String profileImageUri) {
        this.userName = userName;
        this.fullName = fullName;
        this.bio = bio;
        this.profileImageUri = profileImageUri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getProfileImageUri() {
        return profileImageUri;
    }

    public void setProfileImageUri(String profileImageUri) {
        this.profileImageUri = profileImageUri;
    }
}