server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foundbuddy
    username: foundbuddy
    password: foundbuddy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
